name: Parkour
version: 4.8
description: The original and most powerful Parkour plugin available
softdepend: [Vault, BountifulAPI]
author: A5H73Y
main: me.A5H73Y.Parkour.Parkour
website: http://www.mcparkour.co.uk/
commands:
  parkour:
    aliases: [pa, pkr]
    description: Parkour commands