name: Parkour
version: 5.0
description: The original and most powerful Parkour plugin available
softdepend: [Vault, BountifulAPI]
author: A5H73Y
main: me.A5H73Y.Parkour.Parkour
website: http://www.mcparkour.co.uk/
api-version: 1.13
commands:
  parkour:
    aliases: [pa, pkr]
    description: Parkour commands