CREATE TABLE IF NOT EXISTS time (
    timeId INTEGER PRIMARY KEY AUTOINCREMENT,
    courseId INTEGER NOT NULL,
    playerId CHAR(36) NOT NULL,
    time DECIMAL(13,0) NOT NULL,
    deaths INT(5) NOT NULL,
    achieved TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY (courseId) REFERENCES course(courseId) ON DELETE CASCADE ON UPDATE CASCADE
);
