CREATE TABLE IF NOT EXISTS time (
    timeId INTEGER PRIMARY KEY AUTO_INCREMENT,
    courseId INTEGER NOT NULL,
    playerId CHAR(36) CHARACTER SET ascii NOT NULL,
    time DECIMAL(13,0) NOT NULL,
    deaths INT(5) NOT NULL,
    achieved TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY (courseId) REFERENCES course(courseId) ON DELETE CASCADE ON UPDATE CASCADE
);
