package me.A5H73Y.Parkour.Enums;
/**
 * This work is licensed under a Creative Commons 
 * Attribution-NonCommercial-ShareAlike 4.0 International License. 
 * https://creativecommons.org/licenses/by-nc-sa/4.0/
 *
 * @author A5H73Y
 */

public enum TransparentBlocks {
	ACACIA_FENCE,
	ACACIA_FENCE_GATE,
	ANVIL,
	BEACON,
	BIRCH_FENCE,
	BIRCH_FENCE_GATE,
	BLACK_SHULKER_BOX,
	BLUE_SHULKER_BOX,
	BROWN_SHULKER_BOX,
	CAULDRON,
	COBBLE_WALL,
	CYAN_SHULKER_BOX,
	DARK_OAK_FENCE,
	DARK_OAK_FENCE_GATE,
	END_ROD,
	FENCE,
	FENCE_GATE,
	GLASS,
	GLOWSTONE,
	GRAY_SHULKER_BOX,
	GREEN_SHULKER_BOX,
	ICE,
	IRON_FENCE,
	JUNGLE_FENCE,
	JUNGLE_FENCE_GATE,
	LADDER,
	LEAVES,
	LEAVES_2,
	LIGHT_BLUE_SHULKER_BOX,
	LIME_BLUE_SHULKER_BOX,
	MAGENTA_SHULKER_BOX,
	NETHER_FENCE,
	ORANGE_SHULKER_BOX,
	PINK_SHULKER_BOX,
	PURPLE_SHULKER_BOX,
	RED_SHULKER_BOX,
	SEA_LANTERN,
	SILVER_SHULKER_BOX,
	SPRUCE_FENCE,
	SPRUCE_FENCE_GATE,
	STAINED_GLASS,
	STAINED_GLASS_PANE,
	STATIONARY_WATER,
	THIN_GLASS,
	TNT,
	WATER_LILY,
	WHITE_SHULKER_BOX,
	YELLOW_SHULKER_BOX

}
