name: Build

on:
  push:
    branches: [ '7.0' ]
      #  pull_request:
      #    branches: [ '7.0' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repo

    - name: Set up JDK 11 (LTS)
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn install

    - uses: actions/upload-artifact@v2
      name: Upload Artifact
      with:
        name: Parkour.jar
        path: target/Parkour-*.jar
